"""Data loader: re-export the hand-reviewed multiple-route mapping.

The canonical source is ../../data/multi_route_map.json, which is generated by
figures/plot_application_donut.py from its annotated MULTI_ROUTE_MAP dict (the
single editable source of truth). This loader just streams it to the dashboard
so the applications page can unpack `multiple`-coded psychedelic routes with
exactly the same mapping the manuscript donut figure uses.
"""
import json
import sys
from pathlib import Path

# This file lives at dashboard/src/data/; the canonical JSON is at
# publication/data/multi_route_map.json (three parents up, then data/).
HERE = Path(__file__).resolve().parent
SRC = HERE.parents[2] / "data" / "multi_route_map.json"

data = json.loads(SRC.read_text()) if SRC.exists() else {}
json.dump(data, sys.stdout, ensure_ascii=False, separators=(",", ":"))
